### PR TITLE
fix ldap build

### PR DESCRIPTION
**Pull request by BcTpe4HbIu**

### CODE REVIEW

**Comment by alexharpin** [comment]
Thanks, well spotted!

**Comment by dmbaturin** [comment]
Can anyone find a bug it's associated with or create a new one?

**Comment by alexharpin** [comment]
Took me a while to spot it, but it's for bug #350.  The --with-ldap option wasn't being passed to configure.  I added that to the merge commit as it wasn't in the original commit message.  I've cherry-picked it back into Helium as well.

**Comment by dmbaturin** [comment]
Cool, thanks!

**Pull request merged**
